### ISSUE TITLE
support for ".openInCloudStore" method

### ISSUE THREAD

**Issue by williampauljones1** [KeepingFoundThingsFound/itemMirror#66]
across all apps,, as supported through the item driver targeting a specific store, should be support to open the subfolder (or possibly the file too?) for a displayed  association in the cloud store provider (e.g., in a web page in a new tab as generated by the could store provider such as Google Drive or Dropbox).

This would argue for a new itemMirror method: .openInCloudStore

Note: This method serves several purposes:
1. more direct viewing/manipulation of the subfolder (or file) in the cloud service store.
2. indirect path (in Dropbox) towards a Dropbox option to open a subfolder on the desktop. This is provided in the Drobpox UI but not exposed in the API).   What about Google Drive?

**Comment by thorsteinson** [comment]
Implemented and fixed in latest commit. Although the name of the method is currently `getPublicURL`. The ItemMirror library shouldn't be doing any opening, just giving the relevant information back to apps so that they can actually open things.

@brandonthepvongsa, @LegalArgumentException Updating the library to the newest version on git should fix the issues you were having with the method not being recognized. I was able to test on the latest version of FolderDocs and get it working properly.
