### ISSUE TITLE
Cloud store authentication does  not seem to work from the Safari browser

### ISSUE THREAD

**Issue by williampauljones1** [KeepingFoundThingsFound/itemMirror#67]
(Per issue #16 in the itemMirror showcase repository)
also doesn't seem to work with IE (but this is not as important.
This is priority 1 since many of the "jurors" for final review of the paper have Macs

Note: per our discussions on Mondays, it is my understanding that validation happens via the itemDriver for a given cloud store (e.g., Dropbox or Google Drive). and that this should occur via a pop-up dialog (vs. a separate window).. But do web browsers vary in their support for a pop-up dialog to authenticate? this is somewhat worrisome...

**Comment by thorsteinson** [comment]
I'll look into this as soon as I finish with classes for the day, I can test Safari on the Lab machines in the iSchool.

**Comment by thorsteinson** [comment]
Okay, I've found a solution to the problem! The issue appears to be coming from the fact that there are several nested calls occurring before the Google sign-in code calls `window.open`. The solution is to flatten this so that the sign-in function is called immediately within the click handler. I've come up with a temporary solution where users click two buttons in order to properly authenticate, although this could probably be redone as a single click by using jQuery and dynamically changing the buttons.

@LegalArgumentException, @brandonthepvongsa, the latest commit to FolderDocs has this working. Feel free to implement a more elegant solution in the meantime or we can work together to make this better tomorrow when we meet.

**Comment by brandonthepvongsa** [comment]
Interesting, we can definitely try to work up a more elegant solution tomorrow when we meet.
